file:
  input: employee-list.csv

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: debug
    org.springframework.batch.item.database: debug

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/springbatchlab
    username: javalab
    password: pwd@123
